### ISSUE TITLE
Report maintenance status to CR status field

### ISSUE THREAD

**Issue by rawagner** [kubevirt/node-maintenance-operator#16]
It would be nice if maintenance status is reported into CR status field. The CR represents a request that we want to put node under maintenance but we do not know when the node is actually ready (pods have been evicted etc).

**Comment by yanirq** [comment]
@rawagner what status field values do you consider crucial here ?

**Comment by rawagner** [comment]
I'd like to know when
1. operator started the maintenance
2. operator finished all actions (all pods are evicted etc.) and node is in maintenance mode

**Comment by yanirq** [comment]
>     2. operator finished all actions (all pods are evicted etc.) and node is in maintenance mode
Keep in mind that there will be scenarios that not all pods will be evicted (due to PDB for example).
Once a CR for node maintenance is created and intercepted by the controller  - the node is under maintenance de facto.  It will pull out of maintenance once that CR is deleted and processed by the controller successfully , e.g.  node is scheduleable again and CR is deleted.  
Thus a status of complete might indicate the state you mentioned above.
