### ISSUE TITLE
Namespace.yml file not included in deploy folder

### ISSUE THREAD

**Issue by DirectedSoul1** [kubevirt/node-maintenance-operator#21]
When following the README file, under the section:

**Build and run the operator** 
```
$ kubectl create -f deploy/crds/namespace.yaml
```
Gives an error because the namespace.yaml file does not exist in the mentioned path/folder
```
kubectl create -f deploy/crds/namespace.yaml
error: the path "deploy/crds/namespace.yaml" does not exist
```

**Comment by yanirq** [comment]
Right, the path is not correct for the example, it should be deploy/namespace.yaml
This section of deployment might need to be fine tuned to hold written down examples instead of using files directly since the namespace is up to the user (where he wants the operator to run).
The namespace should also match the service account namespace field (under deploy/service_account.yaml)
